aea.f doxygen updates (Part of #77)
NOAA-EMC/NCEPLIBS-w3emc pull request #86
Opened 2021-07-20 18:52 UTC by BrianCurtis-NOAA

Update Doxygen with proper `@params` and `@notes`. Fixes dates where authors are listed.

Fixes #85

2021-07-20 18:53 UTC, BrianCurtis-NOAA commented
@edwardhartnett I can't add reviewers or assign to myself (do i need to be added somewhere or to some group?)

2021-07-20 20:44 UTC, edwardhartnett requested changes

2021-07-20 20:44 UTC, edwardhartnett commented on src/aea.f
> +C> @author desmarais @date 11-29-1982
Use full name if known. If not, ask around for who "Desmarais" is...

2021-07-20 20:44 UTC, edwardhartnett commented on src/aea.f
> +C> @date 11-29-1982  @author desmarais
We don't use the author tag in the Program history log section, or the date tag. See some of the other PRs for examples.

2021-07-20 20:44 UTC, edwardhartnett commented on src/aea.f
> +C>   Argument list:
Remove this line. Doxygen clearly labels the arguments, so we don't need to do that.

2021-07-20 20:44 UTC, edwardhartnett commented on src/aea.f
> +C>   @param[in] NC integer,  contains character count to convert.
Only need one space after the comma.

2021-07-20 20:44 UTC, edwardhartnett commented on src/aea.f
> +C>   - aea converts data at a rate of 1.5 million characters per sec.
Whenever a function or subroutine name appears, use parens after it, which will cause a hyperlink to be automatically generated. So:
`  - aea() converts data at a rate of 1.5 million characters per sec.
`

2021-07-21 14:20 UTC, edwardhartnett commented
@BrianCurtis-NOAA let's move this along...

We need to get about 5 files done per day to make basic progress with this repo...

2021-07-21 16:49 UTC, BrianCurtis-NOAA commented
@edwardhartnett Working on finding out the first names in the author list. Does this block it or can i add them later?

2021-07-21 16:58 UTC, edwardhartnett approved these changes

2021-07-21 17:00 UTC, edwardhartnett commented
We don't need to find out first names to proceed. Ask around and we will press forward. When we find out, start using first names.

I really don't mind much about the PROGRAM HISTORY LOG section, the place where first names are important are the author tags.

I have approved this one, and will merge it. Pick another file and doxygenate it, and put up a new PR.

2021-07-21 17:00 UTC, merged