Doxygen updates for gbyte.f, part of #77
NOAA-EMC/NCEPLIBS-w3emc pull request #88
Opened 2021-07-22 17:55 UTC by BrianCurtis-NOAA

Doxygen updates for gbyte.f

Part of #77

2021-07-22 17:56 UTC, BrianCurtis-NOAA commented
@Hang-Lei-NOAA @edwardhartnett @GeorgeGayno-NOAA

2021-07-23 00:19 UTC, edwardhartnett requested changes

2021-07-23 00:19 UTC, edwardhartnett commented on src/gbyte.f
> +C>                   byte.
Remove the extra whitespace before "byte", and do the same for all the other lines of documentation. One space is all that is ever needed.

2021-07-23 17:02 UTC, edwardhartnett approved these changes

2021-07-27 05:20 UTC, merged