Doxygen for getgbe.f getgbeh.f getgbem.f getgbemh.f getgbemn.f (Part of #77)
NOAA-EMC/NCEPLIBS-w3emc pull request #91
Opened 2021-07-29 17:20 UTC by BrianCurtis-NOAA

Doxygen work for the following:

getgbe.f
getgbeh.f
getgbem.f
getgbemh.f
getgbemn.f

Part of #77

2021-07-29 17:58 UTC, edwardhartnett requested changes

2021-07-29 17:58 UTC, edwardhartnett commented on src/getgbeh.f
> +C>Read a grib index file (or optionally the grib file itself) to get
Put a space between the C> and the start of text. So:

`C> Read a grib index file (or optionally the grib file itself) to get
`

2021-07-29 19:23 UTC, edwardhartnett approved these changes

2021-07-30 19:20 UTC, edwardhartnett approved these changes

2021-08-02 17:33 UTC, BrianCurtis-NOAA commented
@Hang-Lei-NOAA waiting on your approval before I merge.

2021-08-02 17:56 UTC, Hang-Lei-NOAA approved these changes

2021-08-02 18:01 UTC, merged